name: Notify Commit

on:
  push:
    branches: [master]

jobs:
  notify:
    uses: swiftyspiffy/.github/.github/workflows/notify-commit.yml@main
    secrets:
      TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
      NTFY_SERVER_URL: ${{ secrets.NTFY_SERVER_URL }}
