name: Notify Commit

on:
  push:
    branches: [master]

jobs:
  notify:
    uses: swiftyspiffy/.github/.github/workflows/notify-commit.yml@main
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
      NTFY_SERVER_URL: ${{ secrets.NTFY_SERVER_URL }}